feat: add 'max beds' option for houses.
opentibiabr/remeres-map-editor pull request #45
Opened 2023-08-26 19:57 UTC by luanluciano93

Credits: @dex-89

2023-08-28 22:43 UTC, dudantas approved these changes

2023-09-28 03:27 UTC, dudantas commented
The build is broken, it needs to be fixed so we can merge

2023-09-28 03:28 UTC, dudantas requested changes
The build is broken, it needs to be fixed so we can merge

2023-09-29 18:51 UTC, majestyotbr approved these changes

2023-10-07 00:28 UTC, dudantas approved these changes

2023-10-07 20:51 UTC, merged